Implemented signup form
Himanshusingh770/Poll-management-app pull request #2
Opened 2024-10-18 12:21 UTC by Himanshusingh770

2024-10-22 09:36 UTC, PiyushMangla commented on src/Components/SucessModel.jsx
> +      <p>Your account has been created successfully. You can now log in.</p>
use props for message

2024-10-22 09:36 UTC, PiyushMangla commented on src/Components/SucessModel.jsx
> +  const handleOkClick = () => {
use prop for ok click

2024-10-22 09:36 UTC, PiyushMangla commented on src/Components/SucessModel.jsx
> +        OK
use prop for button text

2024-10-22 09:38 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +  const [toastMessage, setToastMessage] = useState(''); // for internal server 500 error
use object for toast data all 3in one

2024-10-22 09:38 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +  const [showModal, setShowModal] = useState(false);
which modal change name

2024-10-22 09:39 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +  const [showPassword, setShowPassword] = useState(false);
use object for these two too password and confirm password

2024-10-22 09:40 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +      .unwrap()
use try catch

2024-10-22 09:40 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +  const toggleConfirmPasswordVisibility = () =>
create single function for both toggle

2024-10-22 09:42 UTC, PiyushMangla commented on src/Pages/SignUpForm.jsx
> +              <Form.Label>Password</Form.Label>
create a separate component for password field and use from there.
Its not looking nice

2024-10-22 09:43 UTC, PiyushMangla commented on src/slices/authSlice.jsx
> +    roles: [],
why its here

2024-10-23 05:57 UTC, yuvrajInno commented on src/Components/PasswordField.jsx
> +const PasswordField = ({ label, name, value, onChange, error, showPassword, toggleVisibility }) => {
showpassword , togglevisibility should not used be as props

2024-10-23 05:57 UTC, yuvrajInno commented on src/Components/SucessModel.jsx
> +        <p>Your account has been created successfully. You can now log in.</p>
Why not prop?

2024-10-23 05:59 UTC, yuvrajInno commented on src/Pages/SignUpForm.jsx
> +  const [showOkModal, setshowOkModal] = useState(false);
change variable name

2024-10-23 06:22 UTC, yuvrajInno commented on src/Components/TostMassege.jsx
> -import React from 'react';
correct component name

2024-10-23 06:22 UTC, yuvrajInno commented on src/Components/SucessModel.jsx
> +import React from 'react';
correct component name

2024-10-23 06:22 UTC, yuvrajInno commented on src/Components/ButtonModel/CustomButtonModel.jsx
> +import React from 'react';
change component name why it has model in it?

2024-10-23 07:29 UTC, yuvrajKaexpertise requested changes

2024-10-23 07:29 UTC, yuvrajKaexpertise commented on src/App.css
> +    border: none;
you are using tailwind CSS, so why are there too many custom styles? @Himanshusingh770

2024-10-23 07:29 UTC, yuvrajKaexpertise commented on src/Data/roles.json
> +[
why this static data? @Himanshusingh770

2024-10-23 07:29 UTC, yuvrajKaexpertise commented on src/Pages/LoginForm.jsx
> +import '../App.css';
why app.css imported in LoginForm? @Himanshusingh770

2024-10-23 07:29 UTC, yuvrajKaexpertise commented on src/Pages/SignUpForm.jsx
> +import '../App.css';
same here

2024-10-23 07:29 UTC, yuvrajKaexpertise commented on src/Pages/SignUpForm.jsx
> +  }, [dispatch]);
blank use effect ? @Himanshusingh770

2024-10-23 13:52 UTC, merged